{% set name = "itermate" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/itermate-{{ version }}.zip
  sha256: 5ee758cbb363493156cee7a29effc2b148a1a19d2be3097e92fc824991901e2a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - itermate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hweickert/itermate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Iterator / Generator tools'
  description: |
    Iterator-tools for functional programming.
  doc_url: https://github.com/hweickert/itermate
  dev_url: https://github.com/hweickert/itermate

extra:
  recipe-maintainers:
    - jan-janssen
